#!/bin/bash

echo "🚀 Configuration Backend Railway"
echo "================================="
echo ""

echo "📋 Étapes à suivre:"
echo ""
echo "1️⃣ Aller sur Railway Dashboard:"
echo "   https://railway.app/project/6544d82c-c677-4678-b2e9-465dfdd4970d"
echo ""
echo "2️⃣ Vérifier les services déployés:"
echo "   - seka-frontend ✅"
echo "   - seka-backend (à vérifier)"
echo "   - Postgres (à vérifier)"
echo ""
echo "3️⃣ Si PostgreSQL n'existe pas:"
echo "   - Cliquez '+ New'"
echo "   - Sélectionnez 'Database' → 'PostgreSQL'"
echo "   - Attendez le déploiement"
echo ""
echo "4️⃣ Configurer le Backend:"
echo "   - Cliquez sur le service 'seka-backend'"
echo "   - Onglet 'Variables'"
echo "   - Ajoutez: DATABASE_URL = \${{Postgres.DATABASE_URL}}"
echo "   - Ajoutez: REDIS_URL = redis://localhost:6379/0 (ou Redis Railway si déployé)"
echo ""
echo "5️⃣ Vérifier start.sh dans le backend:"
echo "   - Doit contenir: python migrate.py"
echo "   - Puis: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "6️⃣ Redéployer le backend:"
echo "   - Cliquez 'Deploy' ou push un commit"
echo ""
echo "================================="
echo ""
echo "🧪 Test après déploiement:"
echo ""
echo "curl -X POST https://api.sekagestion.com/api/v1/auth/login \\"
echo "  -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "  -d 'username=admin@seka.app&password=test'"
echo ""
echo "Si vous obtenez 401 (Incorrect credentials) au lieu de 500,"
echo "c'est que la base de données fonctionne ! ✅"
echo ""
