#!/bin/bash

echo "🔍 Finding Railway Direct URL"
echo "=============================="
echo ""
echo "This script will help you bypass Cloudflare temporarily"
echo "to test if your backend is working correctly."
echo ""
echo "📋 Steps to get Railway direct URL:"
echo ""
echo "1. Go to https://railway.app/dashboard"
echo "2. Select your SEKA Backend service"
echo "3. Go to Settings > Networking"
echo "4. Look for 'Public Networking' section"
echo "5. Copy the Railway-provided URL (e.g., seka-backend-production.up.railway.app)"
echo ""
echo "Then, test it with:"
echo ""
echo "  curl https://YOUR-RAILWAY-URL.up.railway.app/health"
echo ""
echo "If this works (returns 200 OK), your backend is fine and the issue is Cloudflare."
echo ""
echo "To use the Railway URL temporarily in your frontend:"
echo ""
echo "1. Edit frontend/.env.local:"
echo "   NEXT_PUBLIC_API_BASE_URL=https://YOUR-RAILWAY-URL.up.railway.app"
echo ""
echo "2. Restart your frontend dev server"
echo ""
echo "⚠️  This is ONLY for testing. Configure Cloudflare properly for production!"
echo ""
