"""Merge mobile_money and fix_supplier_contact

Revision ID: 7c9e8756f11a
Revises: 20251217_mobile_money_001, 20251220_fix_supplier_contact
Create Date: 2026-01-17 16:28:08.899965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9e8756f11a'
down_revision = ('20251217_mobile_money_001', '20251220_fix_supplier_contact')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
