"""Merge supplier_name into main branch

Revision ID: 8cfa9dbe9ee5
Revises: 7c9e8756f11a, 20260116_supplier_name
Create Date: 2026-01-17 16:28:36.875113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfa9dbe9ee5'
down_revision = ('7c9e8756f11a', '20260116_supplier_name')
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
